modLoader="javafml" 
loaderVersion="[28,)" 
#issueTrackerURL=""

[[mods]] 
modId="custom_villagers"
version="${file.jarVersion}"
displayName="Custom Villagers" 
#updateJSONURL=""
authors="grimmauld" 
description='''
Minecraft Mod to easily add and modify villagers'''

[[dependencies.custom_villagers]] 
    modId="forge"
    mandatory=true 
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.custom_villagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"